[package]
name = "german-invoice"
version = "0.4.0"
compiler = "0.10.0"
entrypoint = "lib.typ"
repository = "https://github.com/2color/typst-invoice"
authors = ["Daniel Norman <@2color>"]
license = "MIT-0"
description = "Minimalistic invoice for germany based freelancers"
keywords = ["invoice", "german", "banking"]
categories = ["layout", "office"]
disciplines = []

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
